---
title: "DataFest-Xiaoxiao Wu & Meria"
---

# Mental health

```{r,echo=T, eval=T,cache=T, message=F,warning=F}
plot(gtrendsR::gtrends(keyword = ("mental health"), geo = "CA", time = "2020-01-01 2020-06-08"))
plot(gtrendsR::gtrends(keyword = ("mental health"), geo = "CA", time = "2019-01-01 2019-06-08"))
# search hits in 2020 are generally higher than ones in 2019
```

```{r,echo=T, eval=T,cache=T, message=F,warning=F}
#Shopping Stores near me VS online shopping
plot(gtrendsR::gtrends(keyword = c("stores near me + shopping mall+ shopping center","online shopping"), geo = "CA", time = "2020-01-01 2020-06-08")) #integrated index
```

```{r,echo=T, eval=T,cache=T, message=F,warning=F}
# Hair Salon
plot(gtrendsR::gtrends(keyword = c("hair cut","hair salon"), geo = "CA", time = "2020-01-01 2020-06-08"))
```

```{r,echo=T, eval=T,cache=T, message=F,warning=F}
#personal hygiene and health
plot(gtrendsR::gtrends(keyword = c("Mask + Hand sanitizer + Toilet paper"), time = "2020-01-01 2020-06-08")) #integrated index
plot(gtrendsR::gtrends(keyword = c("Mask","Hand sanitizer","Toilet paper"), geo = "CA", time = "2020-01-01 2020-06-08"))
# What's going on in April for the search term of "mask"?
```

```{r,echo=T, eval=T,cache=T, message=F,warning=F}
plot(gtrendsR::gtrends(keyword = c("baking + home yoga + homer exercise + home meditation + online shopping + hair cut", "stores near me + beach near me + shopping mall + hiking + park + hair salon"), time = "2020-01-31 2020-06-10")) #integrated index

```
